### ISSUE TITLE
 Requesting for Attachment of Document

### ISSUE THREAD

**Issue by shanmuga1608** [sornavel01/WhatUp_Devlopment#4]
Dear Sornavel!

**It would be grateful app is capable of attachment the document as well.

Kindly add this feature.**

**Comment by sornavel01** [comment]
Hi shanmuga!
**Thanks for valuable suggestion this feature.we will add and let you know.**

**Comment by sornavel01** [comment]
Dear Shanmuga!

Thanks for your valuable suggestion.This feature is going to make our product great.
